import prisma from '../../lib/prisma.js';
import type { EntityType, NotificationType } from '@prisma/client';

// No create endpoint exposed via the API — a Notification is always system-
// generated by whatever event produces it (e.g. an Opportunity stage change,
// see docs/tareas/specredisenosalesv2.md §3.8), never something a user
// submits directly. `message` is pre-rendered here at creation time, not
// computed on read — same reasoning as StatusHistoryEntry snapshotting a
// status's name instead of a live FK, so a later rename doesn't rewrite the
// meaning of an old notification.
export interface CreateNotificationInput {
  tenantId: string;
  userId: string;
  type: NotificationType;
  entityType: EntityType;
  entityId: string;
  message: string;
}

export async function createNotification(input: CreateNotificationInput) {
  return prisma.notification.create({
    data: {
      tenantId: input.tenantId,
      userId: input.userId,
      type: input.type,
      entityType: input.entityType,
      entityId: input.entityId,
      message: input.message,
    },
  });
}

const DEFAULT_PAGE_SIZE = 30;

// Unread first, newest first within each group — the bell dropdown's whole
// point is surfacing what still needs attention.
export async function listNotificationsForUser(tenantId: string, userId: string, page = 1, pageSize = DEFAULT_PAGE_SIZE) {
  return prisma.notification.findMany({
    where: { tenantId, userId },
    orderBy: [{ read: 'asc' }, { createdAt: 'desc' }],
    skip: (page - 1) * pageSize,
    take: pageSize,
  });
}

// Separate from the list call so the bell icon's badge count can poll
// cheaply without pulling the full (paginated) row set every time.
export async function countUnreadNotifications(tenantId: string, userId: string): Promise<number> {
  return prisma.notification.count({ where: { tenantId, userId, read: false } });
}

export interface MarkNotificationReadResult {
  success: boolean;
  error?: string;
}

export async function markNotificationRead(id: string, tenantId: string, userId: string): Promise<MarkNotificationReadResult> {
  const existing = await prisma.notification.findUnique({ where: { id } });
  // Ownership check on both tenantId and userId — a notification belongs to
  // exactly one recipient, not the whole tenant, unlike most other
  // tenantId-scoped rows in this app.
  if (!existing || existing.tenantId !== tenantId || existing.userId !== userId) {
    return { success: false, error: 'Notification not found' };
  }
  await prisma.notification.update({ where: { id }, data: { read: true } });
  return { success: true };
}

export async function markAllNotificationsRead(tenantId: string, userId: string): Promise<void> {
  await prisma.notification.updateMany({ where: { tenantId, userId, read: false }, data: { read: true } });
}

// Used by the stalled-deal reminder cron (docs/tareas/specredisenosalesv2.md
// §3.8) to dedup "once per stall episode" without any new schema: the cron
// skips a candidate whose latest matching notification is newer than the
// Opportunity's current stage-entry date (a stage change always writes a
// fresh OpportunityStageHistory row, which naturally invalidates the old
// notification and allows a new one after the next stall). Batched (one
// query for every candidate) so the cron isn't N+1 across a whole tenant.
export async function findLatestNotificationTimestamps(
  tenantId: string,
  type: NotificationType,
  entityType: EntityType,
  entityIds: string[],
): Promise<Map<string, Date>> {
  if (entityIds.length === 0) {
    return new Map();
  }
  const rows = await prisma.notification.findMany({
    where: { tenantId, type, entityType, entityId: { in: entityIds } },
    select: { entityId: true, userId: true, createdAt: true },
  });
  const latest = new Map<string, Date>();
  for (const row of rows) {
    const key = `${row.entityId}:${row.userId}`;
    const current = latest.get(key);
    if (!current || row.createdAt > current) {
      latest.set(key, row.createdAt);
    }
  }
  return latest;
}
