import {
  createInvoice,
  createInvoiceItem,
  deleteDraftInvoice,
  finalizeInvoice,
  listInvoices,
  NORTHSTACK_SENT_METADATA_KEY,
  sendInvoice,
  StripeApiError,
  type StripeInvoice,
} from '../../lib/stripe.js';
import { getActiveConnectionForTenant, markNeedsAttention } from './stripeService.js';
import { centsToStripeAmount, isZeroDecimalCurrency, stripeAmountToCents } from './stripePaymentsService.js';
import { recordActivity } from '../activity/activityLogService.js';
import { stripeInvoiceActivityFieldConfig } from '../activity/fieldConfigs/stripeInvoiceFieldConfig.js';

// Payments v1, Unidad 8 (docs/tareas/specpaymentsv1.md) — send a Stripe-hosted invoice to a
// Company from inside Northstack. Still no local store: Stripe stays the source of truth, same as
// Units 1-7. Company ownership is checked by the route before any of these run.

const MAX_LINES = 20;
const MAX_DESCRIPTION_LENGTH = 200;
const MAX_MEMO_LENGTH = 500;
// Stripe's own ceiling for a single charge in most currencies is 99,999,999 in the smallest unit.
const MAX_AMOUNT_CENTS = 99_999_999;
const REQUEST_ID_PATTERN = /^[A-Za-z0-9-]{8,64}$/;

export class InvoiceValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'InvoiceValidationError';
  }
}

export class CompanyNotLinkedError extends Error {
  constructor() {
    super('This company is not linked to a Stripe customer yet. Link it first, then send the invoice.');
    this.name = 'CompanyNotLinkedError';
  }
}

// A 403 from Stripe on a Restricted Key means "this key lacks that permission", not "this key is
// broken" — so, unlike Units 2-4's withNeedsAttentionTracking, it must NOT flag the whole
// connection as needing attention (every tenant connected before Unidad 8 has a read-only key,
// and their read features keep working fine). Only a 401 (revoked/invalid key) does that.
export class StripeKeyPermissionError extends Error {
  constructor(public readonly access: 'read' | 'write') {
    super(
      access === 'write'
        ? 'Your Stripe key can\'t create invoices. In Stripe, edit the Restricted Key and set "Invoices" to Write, then try again.'
        : 'Your Stripe key can\'t read invoices. In Stripe, edit the Restricted Key and set "Invoices" to at least Read.'
    );
    this.name = 'StripeKeyPermissionError';
  }
}

async function translateStripeError(tenantId: string, error: unknown, access: 'read' | 'write'): Promise<never> {
  if (error instanceof StripeApiError) {
    if (error.status === 401) {
      await markNeedsAttention(tenantId);
    } else if (error.status === 403) {
      throw new StripeKeyPermissionError(access);
    }
  }
  throw error;
}

export interface InvoiceLineInput {
  description: string;
  amountCents: number;
}

export interface SendCompanyInvoiceInput {
  tenantId: string;
  userId: string;
  company: { id: string; name: string; stripeCustomerId: string | null };
  currency: string;
  lines: InvoiceLineInput[];
  daysUntilDue: number;
  memo?: string;
  // Generated by the client once per submit attempt — makes a double-submit/network retry of the
  // same attempt resolve to the same Stripe objects instead of a second invoice.
  requestId: string;
}

export interface SentInvoice {
  id: string;
  number: string | null;
  status: StripeInvoice['status'];
  amountDueCents: number;
  currency: string;
  dueDate: string | null;
  hostedInvoiceUrl: string | null;
  dashboardUrl: string;
  // False when the invoice was created and finalized but Stripe couldn't email it (most often: the
  // Stripe customer has no email on file). The invoice is still valid and payable via
  // hostedInvoiceUrl — the UI tells the user to share that link or send it from Stripe.
  emailSent: boolean;
}

interface NormalizedInvoiceInput {
  currency: string;
  lines: InvoiceLineInput[];
  daysUntilDue: number;
  memo: string | undefined;
}

export function validateInvoiceInput(input: {
  currency: unknown;
  lines: unknown;
  daysUntilDue: unknown;
  memo?: unknown;
  requestId: unknown;
}): NormalizedInvoiceInput {
  if (typeof input.requestId !== 'string' || !REQUEST_ID_PATTERN.test(input.requestId)) {
    throw new InvoiceValidationError('A valid requestId is required.');
  }

  const currency = typeof input.currency === 'string' ? input.currency.trim().toLowerCase() : '';
  if (!/^[a-z]{3}$/.test(currency)) {
    throw new InvoiceValidationError('Currency must be a 3-letter ISO code.');
  }

  if (!Array.isArray(input.lines) || input.lines.length === 0) {
    throw new InvoiceValidationError('Add at least one line item.');
  }
  if (input.lines.length > MAX_LINES) {
    throw new InvoiceValidationError(`An invoice can have at most ${MAX_LINES} line items.`);
  }

  const lines: InvoiceLineInput[] = input.lines.map((raw, index) => {
    const line = (raw ?? {}) as Record<string, unknown>;
    const description = typeof line.description === 'string' ? line.description.trim() : '';
    if (!description) {
      throw new InvoiceValidationError(`Line ${index + 1}: a description is required.`);
    }
    if (description.length > MAX_DESCRIPTION_LENGTH) {
      throw new InvoiceValidationError(`Line ${index + 1}: description is too long (max ${MAX_DESCRIPTION_LENGTH}).`);
    }
    const amountCents = line.amountCents;
    if (typeof amountCents !== 'number' || !Number.isInteger(amountCents) || amountCents <= 0 || amountCents > MAX_AMOUNT_CENTS) {
      throw new InvoiceValidationError(`Line ${index + 1}: amount must be greater than zero.`);
    }
    if (isZeroDecimalCurrency(currency) && amountCents % 100 !== 0) {
      throw new InvoiceValidationError(`Line ${index + 1}: ${currency.toUpperCase()} has no decimals — use a whole amount.`);
    }
    return { description, amountCents };
  });

  const totalCents = lines.reduce((sum, line) => sum + line.amountCents, 0);
  if (totalCents > MAX_AMOUNT_CENTS) {
    throw new InvoiceValidationError('The invoice total is larger than Stripe allows for a single invoice.');
  }

  const daysUntilDue = input.daysUntilDue;
  if (typeof daysUntilDue !== 'number' || !Number.isInteger(daysUntilDue) || daysUntilDue < 0 || daysUntilDue > 365) {
    throw new InvoiceValidationError('Days until due must be a whole number between 0 and 365.');
  }

  let memo: string | undefined;
  if (input.memo !== undefined && input.memo !== null) {
    if (typeof input.memo !== 'string') throw new InvoiceValidationError('Memo must be text.');
    memo = input.memo.trim() || undefined;
    if (memo && memo.length > MAX_MEMO_LENGTH) {
      throw new InvoiceValidationError(`Memo is too long (max ${MAX_MEMO_LENGTH}).`);
    }
  }

  return { currency, lines, daysUntilDue, memo };
}

function dashboardInvoiceUrl(invoiceId: string, apiKeyMode: 'test' | 'live'): string {
  return `https://dashboard.stripe.com/${apiKeyMode === 'test' ? 'test/' : ''}invoices/${invoiceId}`;
}

function formatTotal(amountCents: number, currency: string): string {
  return `${(amountCents / 100).toFixed(2)} ${currency.toUpperCase()}`;
}

// Create draft → attach lines by invoice id → finalize → send. Any failure before finalizing
// deletes the draft, so a failed attempt never leaves a half-built invoice behind in the tenant's
// Stripe. Once finalized, the invoice is real (it has a number and a payment link) — a failure to
// email it after that point is reported as emailSent: false, not as an error.
export async function sendCompanyInvoice(input: SendCompanyInvoiceInput): Promise<SentInvoice> {
  const { currency, lines, daysUntilDue, memo } = validateInvoiceInput(input);
  const customerId = input.company.stripeCustomerId;
  if (!customerId) {
    throw new CompanyNotLinkedError();
  }

  const { apiKey, apiKeyMode } = await getActiveConnectionForTenant(input.tenantId);
  const keyPrefix = `northstack-invoice-${input.requestId}`;

  let draft: StripeInvoice;
  try {
    draft = await createInvoice(
      apiKey,
      {
        customer: customerId,
        currency,
        daysUntilDue,
        description: memo,
        metadata: { [NORTHSTACK_SENT_METADATA_KEY]: 'true', northstack_company_id: input.company.id },
      },
      `${keyPrefix}-create`,
    );
  } catch (error) {
    return translateStripeError(input.tenantId, error, 'write');
  }

  let finalized: StripeInvoice;
  try {
    for (const [index, line] of lines.entries()) {
      await createInvoiceItem(
        apiKey,
        {
          customer: customerId,
          invoice: draft.id,
          amount: centsToStripeAmount(line.amountCents, currency),
          currency,
          description: line.description,
        },
        `${keyPrefix}-line-${index}`,
      );
    }
    finalized = await finalizeInvoice(apiKey, draft.id, `${keyPrefix}-finalize`);
  } catch (error) {
    await deleteDraftInvoice(apiKey, draft.id).catch((cleanupError) =>
      console.error(`Failed to delete draft Stripe invoice ${draft.id} after an error:`, cleanupError)
    );
    return translateStripeError(input.tenantId, error, 'write');
  }

  let sent = finalized;
  let emailSent = true;
  try {
    sent = await sendInvoice(apiKey, finalized.id, `${keyPrefix}-send`);
  } catch (error) {
    console.error(`Stripe invoice ${finalized.id} was finalized but could not be emailed:`, error);
    emailSent = false;
  }

  const amountDueCents = stripeAmountToCents(sent.amount_due, sent.currency);
  const dueDate = sent.due_date ? new Date(sent.due_date * 1000) : null;

  await recordActivity({
    tenantId: input.tenantId,
    entityType: 'stripeInvoice',
    entityId: sent.id,
    entityLabel: sent.number ?? sent.id,
    action: 'create',
    changedByUserId: input.userId,
    after: {
      total: formatTotal(amountDueCents, sent.currency),
      dueDate,
      lineCount: lines.length,
      memo: memo ?? null,
    },
    fieldConfig: stripeInvoiceActivityFieldConfig,
    parentEntityType: 'company',
    parentEntityId: input.company.id,
  });

  return {
    id: sent.id,
    number: sent.number,
    status: sent.status,
    amountDueCents,
    currency: sent.currency,
    dueDate: dueDate?.toISOString() ?? null,
    hostedInvoiceUrl: sent.hosted_invoice_url,
    dashboardUrl: dashboardInvoiceUrl(sent.id, apiKeyMode),
    emailSent,
  };
}

export interface CompanyInvoiceRow {
  id: string;
  number: string | null;
  status: StripeInvoice['status'];
  amountDueCents: number;
  amountRemainingCents: number;
  currency: string;
  createdAt: string;
  dueDate: string | null;
  hostedInvoiceUrl: string | null;
  dashboardUrl: string;
  sentFromNorthstack: boolean;
}

export interface CompanyInvoicesPage {
  invoices: CompanyInvoiceRow[];
  nextCursor: string | null;
}

// Unpaid invoices have no Charge yet, so they never show up in Units 3/6's Charges-based history —
// this is the list that makes them visible. Drafts are left out: a draft was never sent to anyone
// (and one of ours only exists for the seconds between create and finalize).
export async function listCompanyInvoices(
  tenantId: string,
  company: { stripeCustomerId: string | null },
  cursor?: string,
): Promise<CompanyInvoicesPage> {
  if (!company.stripeCustomerId) {
    return { invoices: [], nextCursor: null };
  }

  const { apiKey, apiKeyMode } = await getActiveConnectionForTenant(tenantId);
  let page;
  try {
    page = await listInvoices(apiKey, { customer: company.stripeCustomerId, limit: 20, starting_after: cursor });
  } catch (error) {
    return translateStripeError(tenantId, error, 'read');
  }

  const invoices = page.data
    .filter((invoice) => invoice.status !== 'draft')
    .map((invoice) => ({
      id: invoice.id,
      number: invoice.number,
      status: invoice.status,
      amountDueCents: stripeAmountToCents(invoice.amount_due, invoice.currency),
      amountRemainingCents: stripeAmountToCents(invoice.amount_remaining, invoice.currency),
      currency: invoice.currency,
      createdAt: new Date(invoice.created * 1000).toISOString(),
      dueDate: invoice.due_date ? new Date(invoice.due_date * 1000).toISOString() : null,
      hostedInvoiceUrl: invoice.hosted_invoice_url,
      dashboardUrl: dashboardInvoiceUrl(invoice.id, apiKeyMode),
      sentFromNorthstack: invoice.metadata?.[NORTHSTACK_SENT_METADATA_KEY] === 'true',
    }));

  // Cursor is the last *fetched* id (not the last kept one), so a page ending in drafts still
  // advances correctly.
  const lastFetched = page.data[page.data.length - 1]?.id ?? null;
  return { invoices, nextCursor: page.has_more ? lastFetched : null };
}
